apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: jellyfin
  namespace: media
spec:
  chart: jellyfin
  repo: https://jellyfin.github.io/jellyfin-helm
  targetNamespace: media
  valuesContent: |-
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: cert-issuer
      hosts:
        - host: media.ryzen.me
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: jellyfin-tls
          hosts:
            - media.ryzen.me
    persistence:
      media:
        existingClaim: content-pvc
      cache:
        enabled: true
      config:
        storageClass: retain
