apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-pvc
  namespace: media
  labels:
    app: lidarr-pvc
    recurring-job.longhorn.io/source: enabled
    recurring-job.longhorn.io/recurring-snapshot: enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
