apiVersion: v1
kind: Service
metadata:
  name: media-service
  namespace: media
spec:
  selector:
    app.kubernetes.io/name: media
  ports:
    - port: 8989
      targetPort: 8989
    - port: 8686
      targetPort: 8686
    - port: 7878
      targetPort: 7878
    - port: 8787
      targetPort: 8787
  type: ClusterIP