apiVersion: v1
kind: Service
metadata:
  name: media-service
  namespace: media
spec:
  selector:
    app: media
  ports:
    - name: sonarr
      port: 8989
      targetPort: 8989
    - name: lidarr
      port: 8686
      targetPort: 8686
    - name: radarr
      port: 7878
      targetPort: 7878
    - name: prowlarr
      port: 9696
      targetPort: 9696
    - name: qbittorrent
      port: 8080
      targetPort: 8080