apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-pvc
  namespace: media
  labels:
    app: lidarr-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-pvc
  namespace: media
  labels:
    app: radarr-pvc
    recurring-job.longhorn.io/source: enabled
    recurring-job.longhorn.io/recurring-snapshot: enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readarr-pvc
  namespace: media
  labels:
    app: readarr-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-pvc
  namespace: media
  labels:
    app: sonarr-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi