apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-config
  namespace: media
  labels:
    app: jackett-config
spec:
  storageClassName: retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi