apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-data
  namespace: {{ .Release.Namespace }}
  labels:
    app: arr-data
spec:
  storageClassName: {{ .Values.arr.persistent.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.arr.persistent.size }}