{{ if .Values.qbittorrent.persistent.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbit-data
  namespace: {{ .Release.Namespace }}
  labels:
    app: qbit-data
spec:
  storageClassName: {{ .Values.arr.persistent.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.qbittorrent.persistent.size }}
{{ end }}