apiVersion: v1
kind: ServiceAccount
metadata:
  name: arr-secret-grep
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: arr-secret-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["patch", "update", "get", "create"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: arr-secret-binding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: arr-secret-grep
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: arr-secret-role
  apiGroup: rbac.authorization.k8s.io