apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.arr.persistent.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: arr-data
spec:
  storageClassName: {{ .Values.arr.persistent.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.arr.persistent.size }}
---
{{ if .Values.qbittorrent.persistent.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.qbittorrent.persistent.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: qbit-data
spec:
  storageClassName: {{ .Values.arr.persistent.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.qbittorrent.persistent.size }}
{{ end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: lidarr-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: radarr-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: sonarr-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: prowlarr-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbit-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: qbit-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: bazarr-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi