apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-qbit-service
  namespace: {{ Release.Namespace }}
spec:
  selector:
    app: qbit
  ports:
    - name: qbittorrent
      port: {{ .Values.qbittorrent.service.port }}
      targetPort: {{ .Values.qbittorrent.service.port }}