{{ if .Values.qbittorrent.vpn.secret.existing }}
apiVersion: v1
data:
    WIREGUARD_PRIVATE_KEY:
    WIREGUARD_ADDRESSES:
kind: Secret
metadata:
  name: {{ .Values.qbittorrent.vpn.secret.name }}
  namespace: {{ Release.Namespace }}
{{ end }}